require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'Tool' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Uncomment the next line to disable it.
    # :hermes_enabled => false,
    # Uncomment the next line to use a nightly build of Hermes
    # :hermes_engine_repo => 'https://github.com/facebook/hermes/releases/download',
    # :hermes_engine_tag => 'nightly',
  )

  target 'ToolTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true,
    )
  end
end
