require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '12.4'

target 'Tool' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :production => ENV["PRODUCTION"] == "true",
    :hermes_enabled => false,
    :fabric_enabled => ENV["RCT_NEW_ARCH_ENABLED"] == "1",
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'ToolTests' do
    inherit! :search_paths
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => true
    )
  end
end
